### ISSUE TITLE
findPath returns an object instead of an array

### ISSUE THREAD

**Issue by vhpoet** [interledger/five-bells-sender#64]
Wallet pathfinding broke after updating the sender. Looking at the [code](https://github.com/interledger/five-bells-sender/blob/47a9d1ea3d2ed50ac37dd5ff780dfb6dc156d150/src/index.js#L188-L197) I see that `findPath` doesn't return an array anymore, instead I'm getting an object. Is this an expected behavior? If yes, please update the [doc](https://github.com/interledger/five-bells-sender/blob/47a9d1ea3d2ed50ac37dd5ff780dfb6dc156d150/src/index.js#L186). Also the `setupTransfers` [throws an exception](https://github.com/interledger/five-bells-sender/blob/master/src/payments.js#L16) _[TypeError: payments.forEach is not a function]_ given an object instead of an array.

**Comment by MatthewPhinney** [comment]
I ran into something similar and used the `CONNECTOR_QUOTE_FULL_PATH=true` env variable in the connector to fix it. https://github.com/interledger/five-bells-connector/blob/master/src/controllers/quote.js#L116

**Comment by sentientwaffle** [comment]
Returning a Transfer object is the new (correct) behavior. I'll update the docs.

**Comment by sentientwaffle** [comment]
Oops, miscommunication. `findPath` should still return an array (that is changing soon, but not yet). Like @MatthewPhinney says, to fix the error, set `CONNECTOR_QUOTE_FULL_PATH=true` on the connector[s].

**Comment by vhpoet** [comment]
Thank you @sentientwaffle @MatthewPhinney. Setting `CONNECTOR_QUOTE_FULL_PATH=true` worked.
